services:
    client:
        container_name: abyss-client
        image: node:20-alpine
        working_dir: /app
        volumes:
            - ./client:/app
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev -- --host"

    server:
        container_name: abyss-server
        image: oven/bun:1-alpine
        working_dir: /app
        restart: always
        volumes:
            - ./server:/app
        ports:
            - "3000:3000"
        command: bun run start
        depends_on:
            - mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_DIALECT=${MYSQL_DIALECT}
            - JWT_SECRET=${JWT_SECRET}
            - PORT=${PORT}

    mysql:
        container_name: abyss-mysql
        image: mysql:8.0
        volumes:
            - db_data_abyss:/var/lib/mysql
            - ./server/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        container_name: abyss-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            PMA_HOST: ${PMA_HOST}
            PMA_USER: ${PMA_USER}
            PMA_PASSWORD: ${PMA_PASSWORD}

volumes:
    db_data_abyss:
