version: "3.8"

services:
    client:
        image: node:20-alpine
        working_dir: /app
        volumes:
            - ./client:/app
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev -- --host"
